"""Add topic_id to assessment_question

Revision ID: 266462f4f91a
Revises: 
Create Date: 2026-09-02 23:58:59.811759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266462f4f91a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assessment_question_topic', 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('mitre_technique_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mitre_technique_id', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_assessment_question_topic', type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
