"""Add time_blocks and time_slot

Revision ID: c18f9e369b62
Revises: 266462f4f91a
Create Date: 2026-09-03 00:12:25.734159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18f9e369b62'
down_revision = '266462f4f91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_slot', sa.String(length=100), nullable=True))

    with op.batch_alter_table('weekly_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_blocks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_availability', schema=None) as batch_op:
        batch_op.drop_column('time_blocks')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('roadmap_item', schema=None) as batch_op:
        batch_op.drop_column('time_slot')

    with op.batch_alter_table('project_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mini_project', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
